public class Main {
    public static void main(String[] args) {
        System.out.println("Course 1");
        System.out.println("Theme 1");
        System.out.println("Task 1");
        int numOne = 47;
        int numTwo = 13;
        int division = numOne / numTwo;
        int remainder = numOne % numTwo;
        System.out.println("Результат деления числа " + numOne + " на " + numTwo + ": " + division + " и " + remainder + " в остатке");
        System.out.println("Task 2");
        numOne = 44;
        int figureOne = numOne / 10;
        int figureTwo = numOne - figureOne * 10;
        int sum = figureOne + figureTwo;
        System.out.println("Результат сложения цифр первого и второго разрядов числа " + numOne + ": " + sum);
        System.out.println("Task 3");
        numOne = 345;
        figureOne = numOne / 100;
        figureTwo = (numOne - figureOne * 100) / 10;
        int figureThree = (numOne - figureOne * 100 - figureTwo * 10);
        sum = figureOne + figureTwo + figureThree;
        System.out.println("Результат сложения цифр первого, второго и третьего разрядов числа " + numOne + ": " + sum);
        System.out.println("Task 4");
        int costFlowers = 4899;
        int costPostcard = 157;
        int discount = 10;
        int sumDiscount = (costFlowers + costPostcard) / discount;
        int finalCost = costFlowers + costPostcard - sumDiscount;
        System.out.println("Суммарная стоимость составила " + finalCost + " рублей, с учётом скидки " + sumDiscount + " рублей.");
        System.out.println("Task 5");
        System.out.println("Subtask a");
        int costOranges = 73;
        int costBananas = 95;
        double discountOranges = 0.15;
        int weightOranges = 10;
        int weightBananas = 2;
        double totalCost = weightOranges * costOranges * discountOranges + weightBananas * costBananas;
        System.out.println("Суммарная стоимость покупки с учётом скидки составила: " + totalCost + " рублей.");
        System.out.println("Subtask b");
        int costChampagne = 2870;
        int costBread = 27;
        double discountChampange = 0.5;
        int countChampagne = 7;
        int countBread = 1;
        totalCost = costChampagne * countChampagne * discountChampange + costBread * countBread;
        System.out.println("Суммарная стоимость покупки с учётом скидки составила: " + totalCost + " рублей.");
        System.out.println("Subtask с");
        int costChampignons = 436;
        int costWhiteMushrooms = 578;
        double discountWhiteMushrooms = 0.05;
        double weightChampignons = 2.5;
        double weightWhiteMushrooms = 3.75;
        totalCost = costChampignons * weightChampignons + costWhiteMushrooms * weightWhiteMushrooms * discountWhiteMushrooms;
        System.out.println("Суммарная стоимость покупки с учётом скидки составила: " + totalCost + " рублей.");
        System.out.println("Task 6");
        double x = 0.4;
        double y = 0.87;
        double dataOne = 11 * x + y;
        double dataTwo = (x + 10 * y) - 15 * (x / y);
        System.out.println("Результаты расчётов: " + dataOne + "; " + dataTwo);
    }
}